### ISSUE TITLE
上传mp3播放时主播端和观众端进度不同

### ISSUE THREAD

**Issue by CloudTsang** [netless-io/flat-web#37]
主播端：win10 chrome / electron
观众端：win10 edge/electron  android
"white-web-sdk": "2.11.6"
在demo.netless.link上可以复现，
上传mp3后，暂停播放双方的进度会一致，但是开始播放就又会错开数十秒
这可能是什么原因？
![image](https://user-images.githubusercontent.com/16476350/103117319-cc3c0b00-46a4-11eb-86c1-5dc6d536f138.png)

**Comment by leavesster** [comment]
可以升级音视频插件，目前已增加同步频率。
