### ISSUE TITLE
运行的时候报错 Module not found: Error: Can't resolve '@netless/cursor-tool' in 

### ISSUE THREAD

**Issue by wu0211** [netless-io/flat-web#77]
![image](https://user-images.githubusercontent.com/34398833/110884346-f1452f00-831f-11eb-964a-3d24a796ce50.png)

问一下，这个指令是在哪个目录下运行的

**Comment by BlackHole1** [comment]
在项目的根目录执行，如果还是不行，请把终端的输出保存成 log文件发一下，我们会协助你进行排查

**Comment by future-mine** [comment]
![image](https://user-images.githubusercontent.com/59634187/146862894-961f157f-594c-4ed2-b8ae-915fad23ec7d.png)

**Comment by future-mine** [comment]
I am also getting this error.
No idea of how to fix it.

**Comment by hyrious** [comment]
@future-mine You have to build all packages before running the main app. Simply `yarn && yarn lerna run --parallel build:lib`.

**Comment by future-mine** [comment]
And to run this,
I should to go to whilteboard folder, right?
And I should run yarn dev, I suppose.
![image](https://user-images.githubusercontent.com/59634187/146863842-a2115382-f712-4f41-94cf-607e0a51d5c4.png)
This is what I am getting right now.

**Comment by hyrious** [comment]
That's because your operating system is Windows and the regex to match this file of `@netless/slide-prefetch` failed at `/` with `\`:
https://github.com/netless-io/whiteboard-demo/blob/8042704b6f31227b266d80f3cba9d9a13cf305e9/whiteboard/webpack.config.js#L66-L73

You can manually edit this webpack config to replace `\/` in the regex with `[\/\\]` to fix that.

**Comment by future-mine** [comment]
I will check.
So eventually, I want to replicate the current whiteboard to my application.
Is it possible to use it without lerna?
For example, Can I install the bunch of @netless/... modules just by npm install or yarn add?

**Comment by hyrious** [comment]
Yes you can. These packages are published to npm. BTW, it is also possible to write these components by yourself to make them suit your needs.

**Comment by future-mine** [comment]
That sounds good to me.
Thank you.

**Comment by future-mine** [comment]
![image](https://user-images.githubusercontent.com/59634187/147284027-ade56e5b-4222-45bd-9861-82a04966b6bb.png)
I don't understand what I should as the env variables.
Can anyone help me, please?

**Comment by future-mine** [comment]
And is there any live agora/netless community such as discord?

**Comment by hyrious** [comment]
The variables you quoted are used in the upload-button package.

You can find our Slack group at https://github.com/netless-io/flat.
